services:
  - type: web
    name: portfolio
    env: node
    plan: free
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: node server/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
      - key: PORT
        value: "10000"
      - key: VITE_API_BASE_URL
        value: "https://your-render-url.onrender.com/api"
    routes:
      - path: /
        matchType: prefix
