services:
  - type: web
    name: portfolio
    env: node
    plan: free
    buildCommand: NODE_OPTIONS="--max-old-space-size=4096" npm run build
    startCommand: bash start.sh
    envVars:
      - key: NODE_OPTIONS
        value: --max-old-space-size=4096
      - key: NODE_ENV
        value: production
      - key: NPM_FLAGS
        value: --legacy-peer-deps
